In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [4]:
b = np.array([[1,2,3,4],[5,6,7,8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [5]:
#get dimenstion
b.ndim

2

In [7]:
#get shape
b.shape

(2, 4)

In [8]:
#Get Type
a.dtype

dtype('int32')

In [9]:
#Get size
a.itemsize

4

In [11]:
#Total size
a.size
a.nbytes

16

In [12]:
#Accessing


In [14]:
#get specification [r,c]

b[1,3]

8

In [15]:
#get specific row
b[0,:]

array([1, 2, 3, 4])

In [16]:
b[1,:]

array([5, 6, 7, 8])

In [26]:
#Types of Arrays
np.zeros((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [28]:
#all matrix
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [30]:
#any other number
np.full((2,2),10)

array([[10, 10],
       [10, 10]])

In [33]:
#any othe rnumber(full_line)
np.full(a,4)

array([[[[4, 4, 4, 4],
         [4, 4, 4, 4],
         [4, 4, 4, 4]],

        [[4, 4, 4, 4],
         [4, 4, 4, 4],
         [4, 4, 4, 4]]]])

In [37]:
#random decimal number
np.random.rand(4,2,2)

array([[[0.49975099, 0.81201731],
        [0.99318926, 0.60577505]],

       [[0.36681625, 0.40132863],
        [0.76501892, 0.86825563]],

       [[0.96087489, 0.4777524 ],
        [0.21357964, 0.93561292]],

       [[0.34010935, 0.81669386],
        [0.54554876, 0.18243051]]])

In [42]:
#Random integer values
np.random.randint(7,size=(3,3))

array([[0, 2, 6],
       [2, 1, 5],
       [6, 3, 5]])

In [44]:
#identy matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [46]:
arr= np.array([[1,2,3,4]])
a = np.repeat(arr,4,axis=0)
print(a)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


In [49]:
output = np.ones((5,5))
print(output)
z=np.zeros((3,3))
z[1,1] = 9
print(z)
output [1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [51]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)

[1 2 3]


In [52]:
#Mathmetics
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [53]:
a+2

array([3, 4, 5, 6])

In [54]:
a-2

array([-1,  0,  1,  2])

In [55]:
a*2

array([2, 4, 6, 8])

In [56]:
b = np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])